"""PROPOSED additions to HARDCODED_MAP in sector_map.py — REVIEW ONLY, not wired in.
Generated from the nifty500_by_sector research (2026-07). Paste vetted lines
into HARDCODED_MAP by hand, or ask Claude to apply the approved subset.
"""


# -- _AUTO (+21) --
"ARE&M": _AUTO, "ASAHIINDIA": _AUTO, "ATHERENERG": _AUTO, "BANCOINDIA": _AUTO, "BELRISE": _AUTO, "CRAFTSMAN": _AUTO, "FIEMIND": _AUTO, "FORCEMOT": _AUTO, "GNA": _AUTO, "HYUNDAI": _AUTO, "JKTYRE": _AUTO, "MENONBE": _AUTO, "MUNJALAU": _AUTO, "OLAELEC": _AUTO, "OLECTRA": _AUTO, "RKFORGE": _AUTO, "RML": _AUTO, "SSWL": _AUTO, "TENNIND": _AUTO, "WHEELS": _AUTO, "ZFCVINDIA": _AUTO, 

# -- _BANK (+1) --
"CUB": _BANK, 

# -- _CDUR (+21) --
"ABFRL": _CDUR, "ABLBL": _CDUR, "ASIANPAINT": _CDUR, "BAJAJELEC": _CDUR, "BERGEPAINT": _CDUR, "CELLO": _CDUR, "DMART": _CDUR, "FIRSTCRY": _CDUR, "GOCOLORS": _CDUR, "JSWDULUX": _CDUR, "LENSKART": _CDUR, "PCJEWELLER": _CDUR, "RRKABEL": _CDUR, "SFL": _CDUR, "SOMANYCERA": _CDUR, "STOVEKRAFT": _CDUR, "THANGAMAYL": _CDUR, "TRENT": _CDUR, "VIPIND": _CDUR, "VMART": _CDUR, "VMM": _CDUR, 

# -- _ENR (+9) --
"BBL": _ENR, "DEEPINDS": _ENR, "INOXGREEN": _ENR, "KIRLPNU": _ENR, "KSB": _ENR, "PRAJIND": _ENR, "SKIPPER": _ENR, "SWSOLAR": _ENR, "VOLTAMP": _ENR, 

# -- _FIN (+7) --
"AIIL": _FIN, "ARMANFIN": _FIN, "EMKAY": _FIN, "FUSION": _FIN, "HUDCO": _FIN, "JIOFIN": _FIN, "MONARCH": _FIN, 

# -- _FMCG (+9) --
"ADFFOODS": _FMCG, "BALRAMCHIN": _FMCG, "BBTC": _FMCG, "CLSEL": _FMCG, "DIAMONDYD": _FMCG, "EIDPARRY": _FMCG, "UNITDSPR": _FMCG, "VSTIND": _FMCG, "ZYDUSWELL": _FMCG, 

# -- _HLTH (+1) --
"INDGN": _HLTH, 

# -- _INF (+51) --
"ACE": _INF, "APOLLO": _INF, "ASHOKA": _INF, "BHARTIARTL": _INF, "BHARTIHEXA": _INF, "BIRLACORPN": _INF, "CAPACITE": _INF, "CARTRADE": _INF, "CEMPRO": _INF, "DBL": _INF, "DCXINDIA": _INF, "GATEWAY": _INF, "GPTINFRA": _INF, "GTLINFRA": _INF, "HCC": _INF, "HFCL": _INF, "HONAUT": _INF, "IDEA": _INF, "IGIL": _INF, "INDIACEM": _INF, "INDUSTOWER": _INF, "ISGEC": _INF, "ITI": _INF, "JKLAKSHMI": _INF, "JSWCEMENT": _INF, "JSWINFRA": _INF, "JYOTICNC": _INF, "KPIL": _INF, "MANINFRA": _INF, "MTARTECH": _INF, "MTNL": _INF, "NUVOCO": _INF, "ORIENTCEM": _INF, "PARAS": _INF, "PATELENG": _INF, "PWL": _INF, "QUESS": _INF, "REDINGTON": _INF, "SIMPLEXINF": _INF, "TBOTEK": _INF, "TECHNOE": _INF, "TEJASNET": _INF, "THOMASCOOK": _INF, "TTML": _INF, "UFBL": _INF, "URBANCO": _INF, "VINDHYATEL": _INF, "WABAG": _INF, "WELENT": _INF, "YATRA": _INF, "ZENTEC": _INF, 

# -- _IT (+9) --
"63MOONS": _IT, "CYIENTDLM": _IT, "KELLTONTEC": _IT, "LTM": _IT, "NIITLTD": _IT, "NIITMTS": _IT, "NUCLEUS": _IT, "RAMCOSYS": _IT, "ZAGGLE": _IT, 

# -- _MED (+1) --
"JAGRAN": _MED, 

# -- _MET (+5) --
"MANINDS": _MET, "NSLNISP": _MET, "PRAKASH": _MET, "SARDAEN": _MET, "USHAMART": _MET, 

# -- _PHM (+9) --
"ACUTAAS": _PHM, "ADVENZYMES": _PHM, "APLLTD": _PHM, "BLUEJET": _PHM, "FDC": _PHM, "HIKAL": _PHM, "INNOVACAP": _PHM, "STAR": _PHM, "UNICHEMLAB": _PHM, 


# ==== NO CLEAN BUCKET — your call (left as OTHER unless you decide otherwise) ====

# Capital Goods (7): AIAENG, CARBORUNIV, CPPLUS, GMMPFAUDLR, KAYNES, LMW, SYRMA

# Chemicals (41): AARTIIND, ACI, AETHER, ALKYLAMINE, ANURAS, ATUL, BALAMINES, BAYERCROP, CAMLINFINE, CHAMBLFERT, CLEAN, COROMANDEL, DEEPAKFERT, DEEPAKNTR, FACT, FINEORG, FLUOROCHEM, GHCL, GUJALKALI, HSCL, INDIAGLYCO, JUBLINGREA, KIRIINDUS, LINDEINDIA, NAVINFLUOR, NEOGEN, NFL, NOCIL, PCBL, PIDILITIND, PIIND, RAIN, RCF, ROSSARI, SRF, SUMICHEM, TATACHEM, UPL, VINATIORGA, VISHNU, YASHO

# Diversified (3): 3MINDIA, DCMSHRIRAM, GODREJIND

# Textiles (14): ALOKINDS, ARVIND, FILATEX, HIMATSEIDE, ICIL, KITEX, KPRMILL, NITINSPIN, PAGEIND, SIYSIL, SPAL, TRIDENT, VTL, WELSPUNLIV


# ==== STILL NO DATA AT ALL from this session's research (252 symbols) ====
# 20MICRONS, ABCOTS, ADSL, AEROENTER, AEROFLEX, AGARIND, AGI, AGIIL, ANUP, APCOTEXIND, APEX, AQYLON, ARIS, ARVINDFASN, ASHAPURMIN, ASIANENE, ASKAUTOLTD, ASTEC, ASTRAMICRO, AURIONPRO, AVALON, AVANTEL, AVL, AWFIS, AWHCL, AXISCADES, BAJAJHIND, BALUFORGE, BASF, BBOX, BCG, BCLIND, BEPL, BETA, BFUTILITIE, BHAGCHEM, BLACKBUCK, BLSE, BLUESTONE, BLUSPRING, BOMDYEING, BORORENEW, CARRARO, CARYSIL, CCAVENUE, CEIGALL, CENTUM, CHEMPLASTS, CMSINFO, CONFIPET, COSMOFIRST, CRIZAC, CUPID, DAMCAPITAL, DCAL, DCW, DIACABS, DJML, DLINKINDIA, DREDGECORP, DSSL, DYCL, DYNAMATECH, E2E, EFCIL, EIEL, EIMCOELECO, EKC, ELECTHERM, EMBDL, EMIL, EMSLIMITED, ENTERO, EPACK, EUREKAFORB, EVEREADY, EXICOM, FCL, FINOPB, GALAPREC, GANECOS, GANESHBE, GARFIBRES, GENESYS, GOCLCORP, GODREJAGRO, GPPL, GREAVESCOT, GRINDWELL, GRMOVER, GRWRHITECH, GSFC, GUJTHEM, GULFOILLUB, GULPOLY, HAPPYFORGE, HARDWYN, HARIOMPIPE, HARSHA, HINDOILEXP, HINDWAREAP, HIRECT, HITECH, HLEGLAS, HPL, HUBTOWN, IMFA, INDIGOPNTS, INDNIPPON, INDOBORAX, INDOTHAI, INFOBEAN, INGERRAND, INTERARCH, IOLCP, IONEXCHANG, ITDC, IXIGO, JAICORPLTD, JASH, JAYBARMARU, JAYNECOIND, JGCHEM, JINDRILL, JINDWORLD, JISLJALEQS, JKPAPER, JNKINDIA, JSLL, JTLIND, JYOTISTRUC, KALAMANDIR, KANSAINER, KDDL, KERNEX, KMEW, KRISHANA, KRISHNADEF, KRN, KSCL, LANDMARK, LAXMIDENTL, LINCOLN, LLOYDSENGG, LLOYDSENT, LUXIND, LXCHEM, MAITHANALL, MANALIPETC, MANYAVAR, MARINE, MAYURUNIQ, MBAPL, MOLDTKPAC, MSTCLTD, NACLIND, NARMADA, NAVKARCORP, NELCO, NESCO, NGLFINE, NIBE, NITCO, NORTHARC, NPST, NRBBEARING, ONEPOINT, OPTIEMUS, ORIENTHOT, PARACABLES, PDSL, PGIL, PICCADIL, PNGJL, POCL, POKARNA, POLYPLEX, PRECWIRE, PRIVISCL, QUADFUTURE, RALLIS, RAMRAT, RATNAVEER, RBA, RELTD, RENUKA, RGL, RISHABH, ROLEXRINGS, ROSSTECH, ROTO, RPEL, RPTECH, RTNINDIA, RTNPOWER, SAKAR, SANGHVIMOV, SANSTAR, SEAMECLTD, SEPC, SHAILY, SHARDACROP, SHK, SHRIPISTON, SILVERTUC, SIS, SJS, SKMEGGPROD, SKYGOLD, SMLMAH, SOLEX, SOTL, SOUTHWEST, SPARC, SPECTRUM, SPMLINFRA, SPORTKING, SRM, STALLION, STEELCAS, STEELXIND, STERTOOLS, SUDARSCHEM, SUMEETINDS, SUNFLAG, TARC, TARSONS, TEMBO, TFCILTD, TI, TIMETECHNO, TIRUMALCHM, TRIVENI, TVSHLTD, UDS, UFLEX, UNIECOM, UNIMECH, UNIPARTS, UNIVCABLES, V2RETAIL, VAIBHAVGBL, VENUSPIPES, VERANDA, VIKRAMSOLR, WALCHANNAG, WENDT, WINDMACHIN, WSTCSTPAPR, XPROINDIA, ZOTA, ZUARI
