"""NSE stock universes for the zone scanner.

All tickers are NSE symbols WITHOUT the ".NS" suffix (the scanner appends it
when fetching from yfinance). Special chars (& - _) are kept as-is —
yfinance handles them.

Source: extracted from scanner.pine batches A-M, deduplicated, indices removed.
~500 unique NSE stocks (Nifty 500 + extras).
"""

NIFTY_50 = [
    "ADANIENT", "ADANIPORTS", "APOLLOHOSP", "ASIANPAINT", "AXISBANK",
    "BAJAJ-AUTO", "BAJFINANCE", "BAJAJFINSV", "BEL", "BHARTIARTL",
    "BPCL", "BRITANNIA", "CIPLA", "COALINDIA", "DRREDDY",
    "EICHERMOT", "ETERNAL", "GRASIM", "HCLTECH", "HDFCBANK",
    "HDFCLIFE", "HEROMOTOCO", "HINDALCO", "HINDUNILVR", "ICICIBANK",
    "INDUSINDBK", "INFY", "ITC", "JIOFIN", "JSWSTEEL",
    "KOTAKBANK", "LT", "LICI", "M&M", "MARUTI",
    "NESTLEIND", "NTPC", "ONGC", "POWERGRID", "RELIANCE",
    "SBILIFE", "SBIN", "SHRIRAMFIN", "SUNPHARMA", "TATACONSUM",
    "TATAMOTORS", "TATASTEEL", "TCS", "TECHM", "TITAN",
    "TRENT", "ULTRACEMCO", "WIPRO",
]

# All other NSE stocks from batches B-M (Nifty Next 50 + Nifty 200 + 500)
NIFTY_REST = [
    # Batch B
    "360ONE", "3MINDIA", "ABB", "ACC", "AIAENG", "APLAPOLLO", "AUBANK",
    "AARTIIND", "AAVAS", "ABBOTINDIA", "ACE", "ADANIENSOL", "ADANIGREEN",
    "ADANIPOWER", "ATGL", "AWL", "ABCAPITAL", "ABFRL", "AEGISLOG",
    "AETHER", "AFFLE", "AJANTPHARM", "APLLTD", "ALKEM", "ALKYLAMINE",
    "ALLCARGO", "ALOKINDS", "ARE&M", "AMBER", "AMBUJACEM", "ANANDRATHI",
    "ANGELONE", "ANURAS", "APARINDS", "APOLLOTYRE", "APTUS", "ACI",
    "ASAHIINDIA", "ASHOKLEY", "ASTERDM",
    # Batch C
    "ASTRAZEN", "ASTRAL", "ATUL", "AUROPHARMA", "AVANTIFEED", "DMART",
    "BEML", "BLS", "BSE", "BAJAJHLDNG", "BALAMINES", "BALKRISIND",
    "BALRAMCHIN", "BANDHANBNK", "BANKBARODA", "BANKINDIA", "MAHABANK",
    "BATAINDIA", "BAYERCROP", "BERGEPAINT", "BDL", "BHARATFORG", "BHEL",
    "BIKAJI", "BIOCON", "BIRLACORPN", "BSOFT", "BLUEDART", "BLUESTARCO",
    "BBTC", "BORORENEW", "BOSCHLTD", "BRIGADE", "MAPMYINDIA", "CCL",
    "CESC", "CGPOWER", "CIEINDIA", "CRISIL", "CSBBANK",
    # Batch D
    "CAMPUS", "CANFINHOME", "CANBK", "CAPLIPOINT", "CGCL", "CARBORUNIV",
    "CASTROLIND", "CEATLTD", "CELLO", "CENTRALBK", "CDSL", "CENTURYPLY",
    "ABREL", "CERA", "CHALET", "CHAMBLFERT", "CHEMPLASTS", "CHENNPETRO",
    "CHOLAHLDNG", "CHOLAFIN", "CUB", "CLEAN", "COCHINSHIP", "COFORGE",
    "COLPAL", "CAMS", "CONCORDBIO", "CONCOR", "COROMANDEL", "CRAFTSMAN",
    "CREDITACC", "CROMPTON", "CUMMINSIND", "CYIENT", "DCMSHRIRAM", "DLF",
    "DOMS", "DABUR", "DALBHARAT", "DATAPATTNS",
    # Batch E
    "DEEPAKFERT", "DEEPAKNTR", "DELHIVERY", "DEVYANI", "DIVISLAB", "DIXON",
    "LALPATHLAB", "EIDPARRY", "EIHOTEL", "EPL", "EASEMYTRIP", "ELECON",
    "ELGIEQUIP", "EMAMILTD", "ENDURANCE", "ENGINERSIN", "EQUITASBNK", "ERIS",
    "ESCORTS", "EXIDEIND", "FDC", "NYKAA", "FEDERALBNK", "FACT",
    "FINEORG", "FINCABLES", "FINPIPE", "FSL", "FIVESTAR", "FORTIS",
    "GAIL", "GMMPFAUDLR", "GMRAIRPORT", "GRSE", "GICRE", "GILLETTE",
    "GLAND", "GLAXO", "GLENMARK", "ALIVUS",
    # Batch F
    "MEDANTA", "GPIL", "GODFRYPHLP", "GODREJCP", "GODREJIND", "GODREJPROP",
    "GRANULES", "GRAPHITE", "GESHIP", "GRINDWELL", "GAEL", "ADANIENSOL",
    "FLUOROCHEM", "GUJGASLTD", "GMDCLTD", "GNFC", "GPPL", "GSFC",
    "GSPL", "HEG", "HBLENGINE", "HDFCAMC", "HFCL", "HAPPSTMNDS",
    "HAPPYFORGE", "HAVELLS", "HSCL", "HAL", "HINDCOPPER", "HINDPETRO",
    "HINDZINC", "POWERINDIA", "HOMEFIRST", "HONASA", "HONAUT", "HUDCO",
    "ICICIGI", "ICICIPRULI", "IDBI", "IDFCFIRSTB",
    # Batch G
    "IFCI", "IIFL", "IRB", "IRCON", "ITI", "INDIACEM",
    "INDIAMART", "INDIANB", "IEX", "INDHOTEL", "INDIGOPNTS", "IGL",
    "INDUSTOWER", "NAUKRI", "INOXWIND", "INTELLECT", "INDIGO", "IPCALAB",
    "IOC", "IOB", "IRCTC", "IRFC", "JBCHEPHARM", "JKCEMENT",
    "JBMA", "JKLAKSHMI", "JKPAPER", "JMFINANCIL", "JSWENERGY", "JSWINFRA",
    "JAIBALAJI", "J&KBANK", "JINDALSAW", "JSL", "JINDALSTEL", "JUBLFOOD",
    "JUBLINGREA", "JUBLPHARMA", "JWL", "JUSTDIAL",
    # Batch H
    "JYOTHYLAB", "KPRMILL", "KEI", "KSB", "KAJARIACER", "KPIL",
    "KALYANKJIL", "KANSAINER", "KARURVYSYA", "KAYNES", "KEC", "KFINTECH",
    "KIMS", "LTF", "LTTS", "LICHSGFIN", "LTIM", "LATENTVIEW",
    "LAURUSLABS", "LXCHEM", "LEMONTREE", "LINDEINDIA", "LLOYDSME", "LUPIN",
    "MMTC", "MRF", "MTARTECH", "MGL", "MAHSEAMLES", "M&MFIN",
    "MHRIL", "MAHLIFE", "MANAPPURAM", "MRPL", "MANKIND", "MARICO",
    "KRBL",
    # Batch I
    "MASTEK", "MFSL", "MAXHEALTH", "MAZDOCK", "MEDPLUS", "METROBRAND",
    "METROPOLIS", "MINDACORP", "MSUMI", "MOTILALOFS", "MPHASIS", "MUTHOOTFIN",
    "NATCOPHARM", "NBCC", "NCC", "NHPC", "NLCINDIA", "NSLNISP",
    "NH", "NATIONALUM", "NAVINFLUOR", "NETWORK18", "NAM-INDIA", "NUVAMA",
    "NUVOCO", "OBEROIRLTY", "OIL", "OLECTRA", "OFSS", "PAYTM",
    "PCBL", "PIIND", "PNBHOUSING", "PNCINFRA", "PVRINOX", "PAGEIND",
    "PATANJALI",
    # Batch J
    "PERSISTENT", "PETRONET", "PHOENIXLTD", "PIDILITIND", "PIRAMALFIN", "PPLPHARMA",
    "POLYMED", "POLYCAB", "POONAWALLA", "PFC", "PRAJIND", "PRESTIGE",
    "PRINCEPIPE", "PRSMJOHNSN", "PGHH", "PNB", "QUESS", "RBLBANK",
    "RHIM", "RRKABEL", "RVNL", "RAILTEL", "RAINBOW", "RAJESHEXPO",
    "RKFORGE", "RCF", "RATNAMANI", "RAYMOND", "REDINGTON", "RECLTD",
    "RITES", "RADICO", "ROUTE", "SBFC", "SBICARD", "SBILIFE",
    "SJVN", "SKFINDIA", "RBA", "RTNINDIA",
    # Batch K
    "SRF", "SAFARI", "SAMMAANCAP", "MOTHERSON", "SANOFI", "SAPPHIRE",
    "SAREGAMA", "SCHAEFFLER", "SCHNEIDER", "SHREECEM", "RENUKA", "SHRIRAMFIN",
    "SHYAMMETL", "SIEMENS", "SIGNATURE", "SOBHA", "SOLARINDS", "SONACOMS",
    "SONATSOFTW", "STARHEALTH", "STLTECH", "SUMICHEM", "SPARC", "SUNPHARMA",
    "SUNTV", "SUNDARMFIN", "SUNDRMFAST", "SUNTECK", "SUPREMEIND", "SUZLON",
    "SWANENERGY", "SYNGENE", "SYRMA", "TBOTEK", "TVSMOTOR", "TVSSCS",
    "COHANCE",
    # Batch L
    "TMB", "TANLA", "TATACHEM", "TATACOMM", "TCS", "TATAELXSI",
    "TATAINVEST", "TATAMOTORS", "TATAPOWER", "TATASTEEL", "TATATECH", "TATACONSUM",
    "TECHM", "TEJASNET", "NIACL", "RAMCOCEM", "THERMAX", "TIMKEN",
    "TITAGARH", "TITAN", "TORNTPHARM", "TORNTPOWER", "TRENT", "TRIDENT",
    "TRIVENI", "TRITURBINE", "TIINDIA", "UCOBANK", "UNOMINDA", "UPL",
    "UTIAMC", "UJJIVANSFB", "ULTRACEMCO", "UNIONBANK", "UBL", "UNITDSPR",
    "USHAMART", "VGUARD", "VIPIND",
    # Batch M
    "VAIBHAVGBL", "VTL", "VARROC", "VBL", "MANYAVAR", "VEDL",
    "VIJAYA", "IDEA", "VOLTAS", "WELCORP", "WELSPUNLIV", "WESTLIFE",
    "WHIRLPOOL", "WIPRO", "YESBANK", "ZFCVINDIA", "ZEEL", "ZENSARTECH",
    "ZYDUSLIFE", "ECLERX",
]

# Master list — what the scanner actually iterates over.
# Dedupe just in case any symbol appears in both Nifty 50 and the rest.
ALL_SYMBOLS = sorted(set(NIFTY_50 + NIFTY_REST))
